ALTER TABLE product DROP COLUMN IF EXISTS description;
ALTER TABLE product DROP COLUMN IF EXISTS moq;
ALTER TABLE product DROP COLUMN IF EXISTS poll;
ALTER TABLE product DROP COLUMN IF EXISTS sbu;
ALTER TABLE product DROP COLUMN IF EXISTS stock;
ALTER TABLE product DROP COLUMN IF EXISTS base_price;
ALTER TABLE product DROP COLUMN IF EXISTS mrp;
ALTER TABLE product DROP COLUMN IF EXISTS gst;
ALTER TABLE product DROP COLUMN IF EXISTS warranty;
ALTER TABLE product DROP COLUMN IF EXISTS distributor_price;
ALTER TABLE product DROP COLUMN IF EXISTS product_category;
ALTER TABLE product DROP COLUMN IF EXISTS sub_category;

ALTER TABLE product ALTER COLUMN category TYPE VARCHAR(40);
ALTER TABLE product ADD CONSTRAINT product_category_check CHECK (category IN (
    'INVERTER', 'BATTERY', 'SOLAR', 'ACCESSORY'
));
